name: Build and Deploy Notes Markdown Index

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install pyyaml

      - name: Run Brain Index Generator
        run: |
          python scripts/generate_brain_index.py

      - name: Verify Output Files
        run: |
          test -f output/index.md || (echo "❌ Missing output/index.md" && exit 1)
          test -f output/index.html || (echo "❌ Missing output/index.html" && exit 1)

      - name: Display Output Files (for debugging)
        run: |
          echo "::group::Output Files"
          ls -al output
          echo "::endgroup::"
          echo "::group::Hashes"
          sha256sum output/index.*
          echo "::endgroup::"

      - name: Commit and Push Output (Optional, Optional)
        if: false  # ⛔ Disable if you're deploying via Pages only
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin main
          git reset --hard origin/main
          git add -f output/
          git diff --cached --quiet || git commit -m "Auto-update: Index.md and Index.html"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
